### ISSUE TITLE
Add to DefinitelyTyped

### ISSUE THREAD

**Issue by HatchedMango** [spacejack/hyperscript.d.ts#1]
Consider adding this to the DefinitelyTyped repository. It is a collection of types like this. 
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

**Comment by spacejack** [comment]
Hi, it was added to DT and is installable via npm with:

    npm install -D @types/hyperscript

The version on DT has some improvements over this repo as well. I'll add a note on the readme that this repo is deprecated.
